trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # Cache Cypress binaries
  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  # Install dependencies in root directory and Cypress binary
  - script: |
      npm install
      npx cypress install
    displayName: 'Install dependencies and Cypress binary'

  # Install frontend dependencies and build project
  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Install frontend dependencies and build project'

  # Start frontend server in the background and wait for it to be ready
  - script: |
      cd frontend
      npm start &
      npx wait-on http://localhost:3000
    displayName: 'Start Frontend Server and wait for readiness'

  # Run Cypress E2E tests
  - script: npx cypress run
    displayName: 'Run Cypress E2E Tests'

  # Compile TypeScript files (if applicable)
  - script: |
      tsc -p tsconfig.json
    displayName: 'Compile TypeScript'
