trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # 缓存 Cypress 二进制文件
  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  # 安装项目依赖，包括 Cypress
  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build project'

  # 安装 Cypress 二进制文件
  - script: npx cypress install
    displayName: 'Install Cypress binary'

  # 启动前端服务器，并在后台运行
  - script: |
      npm start &
    displayName: 'Start Frontend Server'

  # 等待服务器启动
  - script: |
      sleep 30  # 等待10秒，确保前端服务器已启动
    displayName: 'Wait for Frontend Server to be ready'

  # 运行 Cypress 测试
  - script: npx cypress run
    displayName: 'Run Cypress E2E Tests'

  # 编译 TypeScript 文件
  - script: tsc -p tsconfig.json
    displayName: 'Compile TypeScript'
