trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # 缓存 Cypress 二进制文件
  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  # 安装项目依赖，包括 Cypress 和 serve
  - script: |
      cd frontend  # 进入 frontend 目录
      npm install  # 安装前端依赖
      npm run build  # 如果需要构建前端
    displayName: 'Install dependencies and build project in frontend'

  # 安装 Cypress 二进制文件
  - script: npx cypress install
    displayName: 'Install Cypress binary'

  # 启动前端服务器，并在后台运行
  - script: |
      cd frontend  # 进入 frontend 目录
      npm start &  # 在后台启动前端服务器
    displayName: 'Start Frontend Server'

  # 使用 wait-on 等待前端服务器启动在端口 3000
  - script: npx wait-on http://localhost:3000
    displayName: 'Wait for Frontend Server to be ready'

  # 运行 Cypress 测试
  - script: |
      cd frontend  # 进入 frontend 目录
      npx cypress run
    displayName: 'Run Cypress E2E Tests'

  # 编译 TypeScript 文件（如果适用）
  - script: |
      tsc -p tsconfig.json
    displayName: 'Compile TypeScript'
