trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  - script: |
      npm install
    displayName: 'Install dependencies in root directory'

  - script: |
      npx cypress install
      chmod +x ./node_modules/.bin/cypress
    displayName: 'Install Cypress binary and set permissions'

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Install dependencies and build project in frontend'

  - script: |
      cd frontend 
      npm start &
      npx wait-on http://localhost:3000  # 等待前端服务端口准备好
    displayName: 'Start Frontend Server and wait for readiness'

  - script: npx cypress run
    displayName: 'Run Cypress E2E Tests in root directory'

  - script: |
      tsc -p tsconfig.json
    displayName: 'Compile TypeScript'
