trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  - script: |
      npm install
    displayName: 'Install dependencies in root directory'

  - script: npx cypress install
    displayName: 'Install Cypress binary'

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Install dependencies and build project in frontend'


  - script: |
      cd frontend 
      npm start &
    displayName: 'Start Frontend Server'

  - script: npx wait-on http://localhost:3000
    displayName: 'Wait for Frontend Server to be ready'

  - script: npx cypress run
    displayName: 'Run Cypress E2E Tests in root directory'

  - script: |
      tsc -p tsconfig.json
    displayName: 'Compile TypeScript'