trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # 缓存 Cypress 二进制文件
  - task: Cache@2
    inputs:
      key: 'cypress-linux-$(Agent.OSArchitecture)-$(Build.SourceVersion)'
      path: $(HOME)/.cache/Cypress
    displayName: 'Cache Cypress binaries'

  # 安装项目依赖，包括 Cypress
  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build project'

  # 安装 Cypress 二进制文件
  - script: npx cypress install
    displayName: 'Install Cypress binary'

  # 列出构建输出目录的内容
  - script: ls -la dist
    displayName: 'List output directory contents'

  # 发布构建输出为构建工件
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'  # Assuming 'dist' is the output directory
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # 运行 Cypress 测试
  - script: npx cypress run
    displayName: 'Run Cypress E2E Tests'

  # 编译 TypeScript 文件
  - script: tsc -p tsconfig.json
    displayName: 'Compile TypeScript'
